<a href="https://colab.research.google.com/github/ahmadsanafarooq/Data-Science-Machine-Learning-Nodebook/blob/main/Practise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#what is python?
# python is HLL used to build website and application
#use to analyze data

In [2]:
name="AHMAD SANA FAROOQ"
age=24
city='Burewala'

In [3]:
print("Name Of Student\n",name)
print("Age of student\n",age)
print("City of student\n",city)

Name Of Student
 AHMAD SANA FAROOQ
Age of student
 24
City of student
 Burewala

In [4]:
#list
name_of_languages=['python','c++','java','html','css']
name_of_languages

['python', 'c++', 'java', 'html', 'css']

In [5]:
name_of_languages[0]

'python'

In [6]:
name_of_languages[2:4]

['java', 'html']

In [7]:
name_of_languages[:3]

['python', 'c++', 'java']

In [8]:
#dictionary
language={
    'Subject':['AI','ML','DS'],
    'Semester':['1ST','2ND','3RD'],
    'Students':['AHMAD','HANNA','ANAS'],
    'age':[24,23,25]
}

In [9]:
print("Subject is ",language['Subject'][0])
print("Semester is ",language['Semester'][0])
print("Name is ",language['Students'][0])
print("Age is ",language['age'][0])

Subject is  AI
Semester is  1ST
Name is  AHMAD
Age is  24

In [10]:
import pandas as pd

In [11]:
#dataframe
language={
    'Subject':['AI','ML','DS'],
    'Semester':['1ST','2ND','3RD'],
    'Students':['AHMAD','HANNA','ANAS'],
    'age':[24,23,25]
}
pd.DataFrame(language)

  Subject Semester Students  age
0      AI      1ST    AHMAD   24
1      ML      2ND    HANNA   23
2      DS      3RD     ANAS   25

In [12]:
city={
    'Cities':['Faisalabad','Lahore','Burewala'],
    'Towns':['Jamilabad','Bahria Town','Pine City'],
    'Shoping Mall':['Imtiaz Mall','Dolphin Mall','Habib Mall']
}
pd.DataFrame(city)

       Cities        Towns  Shoping Mall
0  Faisalabad    Jamilabad   Imtiaz Mall
1      Lahore  Bahria Town  Dolphin Mall
2    Burewala    Pine City    Habib Mall

In [13]:
#load dataset
data=pd.read_csv("/content/Crime_Incidents_in_2024.csv")

In [14]:
#top values of data use head
data.head()

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
0,396384.27,137427.7600,24054605,2024/04/12 14:24:15+00,DAY,OTHERS,THEFT F/AUTO,1100 - 1199 BLOCK OF 18TH STREET NW,396384.270000,137427.760000,...,010700 1,10700.0,Precinct 17,38.904699,-77.041686,GOLDEN TRIANGLE,2024/04/12 06:33:00+00,2024/04/12 08:59:00+00,666213423,NaN
1,395709.91,137490.9400,24056000,2024/04/14 23:56:40+00,EVENING,OTHERS,THEFT/OTHER,2200 - 2299 BLOCK OF M STREET NW,395709.910000,137490.940000,...,005501 2,5501.0,Precinct 4,38.905265,-77.049461,NaN,2024/04/14 04:00:00+00,NaN,666213424,NaN
2,397497.55,137053.1300,24056385,2024/04/15 17:42:57+00,DAY,OTHERS,THEFT/OTHER,1200 - 1299 BLOCK OF I STREET NW,397497.550000,137053.130000,...,010100 2,10100.0,Precinct 129,38.901328,-77.028849,DOWNTOWN,2024/04/15 14:31:00+00,2024/04/15 15:18:00+00,666213769,NaN
3,400040.61,129046.4721,18060158,2024/07/30 04:00:00+00,MIDNIGHT,GUN,HOMICIDE,400 - 599 BLOCK OF CHESAPEAKE STREET SE,400040.610046,129046.472149,...,009802 2,9802.0,Precinct 125,38.829204,-76.999532,NaN,2018/04/15 16:07:00+00,2018/04/15 17:34:56+00,666236835,NaN
4,397171.11,137408.2500,24013789,2024/01/28 07:33:28+00,MIDNIGHT,OTHERS,THEFT/OTHER,1100 - 1199 BLOCK OF VERMONT AVENUE NW,397171.110000,137408.250000,...,010100 3,10100.0,Precinct 17,38.904526,-77.032614,DOWNTOWN,2024/01/28 06:41:00+00,2024/01/28 07:12:00+00,666239683,NaN

In [15]:
#statistical implementation of data
data.describe()

,X,Y,CCN,XBLOCK,YBLOCK,WARD,DISTRICT,PSA,CENSUS_TRACT,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
count,29295.000000,29295.000000,2.929500e+04,29295.000000,29295.000000,29291.000000,28550.000000,28827.000000,29280.000000,29295.000000,29295.000000,2.929500e+04,0.0
mean,399281.365189,137801.454601,2.412673e+07,399281.365190,137801.454601,4.393602,3.703292,374.842994,7521.588081,38.908067,-77.008292,6.666143e+08,NaN
std,3032.291061,3344.181869,1.624752e+05,3032.291061,3344.181868,2.322873,1.841980,183.751097,34736.612847,0.030124,0.034962,1.575541e+05,NaN
min,390362.150000,127300.240000,5.094764e+06,390362.150000,127300.240000,1.000000,1.000000,101.000000,101.000000,38.813473,-77.111162,6.662134e+08,NaN
25%,397229.000000,136234.280000,2.405873e+07,397229.000006,136234.280000,2.000000,2.000000,207.000000,3500.000000,38.893930,-77.031952,6.665412e+08,NaN
50%,399029.030000,137856.980000,2.411504e+07,399029.030000,137856.979997,5.000000,4.000000,401.000000,7202.000000,38.908569,-77.011192,6.666663e+08,NaN
75%,401206.777300,139815.115000,2.416641e+07,401206.777279,139815.115000,6.000000,5.000000,506.000000,9102.000000,38.926188,-76.986094,6.667370e+08,NaN
max,407806.750900,147365.030000,2.503097e+07,407806.750917,147365.030000,8.000000,7.000000,708.000000,980000.000000,38.994217,-76.910012,6.667763e+08,NaN

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29295 entries, 0 to 29294
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   X                     29295 non-null  float64
 1   Y                     29295 non-null  float64
 2   CCN                   29295 non-null  int64
 3   REPORT_DAT            29295 non-null  object
 4   SHIFT                 29295 non-null  object
 5   METHOD                29295 non-null  object
 6   OFFENSE               29295 non-null  object
 7   BLOCK                 29295 non-null  object
 8   XBLOCK                29295 non-null  float64
 9   YBLOCK                29295 non-null  float64
 10  WARD                  29291 non-null  float64
 11  ANC                   29291 non-null  object
 12  DISTRICT              28550 non-null  float64
 13  PSA                   28827 non-null  float64
 14  NEIGHBORHOOD_CLUSTER  29291 non-null  object
 15  BLOCK_GROUP           29280 non-null  object
 16  CENSUS_TRACT          29280 non-null  float64
 17  VOTING_PRECINCT       29291 non-null  object
 18  LATITUDE              29295 non-null  float64
 19  LONGITUDE             29295 non-null  float64
 20  BID                   5414 non-null   object
 21  START_DATE            29289 non-null  object
 22  END_DATE              27200 non-null  object
 23  OBJECTID              29295 non-null  int64
 24  OCTO_RECORD_ID        0 non-null      float64
dtypes: float64(11), int64(2), object(12)
memory usage: 5.6+ MB

In [17]:
#missing values
data.isnull().sum()

X                           0
Y                           0
CCN                         0
REPORT_DAT                  0
SHIFT                       0
METHOD                      0
OFFENSE                     0
BLOCK                       0
XBLOCK                      0
YBLOCK                      0
WARD                        4
ANC                         4
DISTRICT                  745
PSA                       468
NEIGHBORHOOD_CLUSTER        4
BLOCK_GROUP                15
CENSUS_TRACT               15
VOTING_PRECINCT             4
LATITUDE                    0
LONGITUDE                   0
BID                     23881
START_DATE                  6
END_DATE                 2095
OBJECTID                    0
OCTO_RECORD_ID          29295
dtype: int64

In [18]:
#fill missing values
data['WARD']=data['WARD'].fillna(data['WARD'].mean())
data['ANC']=data['ANC'].fillna(data['ANC'].mode()[0])
data['DISTRICT']=data['DISTRICT'].fillna(data['DISTRICT'].mode()[0])
data.isnull().sum()

X                           0
Y                           0
CCN                         0
REPORT_DAT                  0
SHIFT                       0
METHOD                      0
OFFENSE                     0
BLOCK                       0
XBLOCK                      0
YBLOCK                      0
WARD                        0
ANC                         0
DISTRICT                    0
PSA                       468
NEIGHBORHOOD_CLUSTER        4
BLOCK_GROUP                15
CENSUS_TRACT               15
VOTING_PRECINCT             4
LATITUDE                    0
LONGITUDE                   0
BID                     23881
START_DATE                  6
END_DATE                 2095
OBJECTID                    0
OCTO_RECORD_ID          29295
dtype: int64

In [19]:
#drop missing values
data = data.drop(['PSA','NEIGHBORHOOD_CLUSTER','BLOCK_GROUP','CENSUS_TRACT','VOTING_PRECINCT','BID','START_DATE','END_DATE','OCTO_RECORD_ID'], axis=1)
data.isnull().sum()

X             0
Y             0
CCN           0
REPORT_DAT    0
SHIFT         0
METHOD        0
OFFENSE       0
BLOCK         0
XBLOCK        0
YBLOCK        0
WARD          0
ANC           0
DISTRICT      0
LATITUDE      0
LONGITUDE     0
OBJECTID      0
dtype: int64

In [20]:
#handle inconsistense data
data['WARD']=data['WARD'].astype(int)

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29295 entries, 0 to 29294
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           29295 non-null  float64
 1   Y           29295 non-null  float64
 2   CCN         29295 non-null  int64
 3   REPORT_DAT  29295 non-null  object
 4   SHIFT       29295 non-null  object
 5   METHOD      29295 non-null  object
 6   OFFENSE     29295 non-null  object
 7   BLOCK       29295 non-null  object
 8   XBLOCK      29295 non-null  float64
 9   YBLOCK      29295 non-null  float64
 10  WARD        29295 non-null  int64
 11  ANC         29295 non-null  object
 12  DISTRICT    29295 non-null  float64
 13  LATITUDE    29295 non-null  float64
 14  LONGITUDE   29295 non-null  float64
 15  OBJECTID    29295 non-null  int64
dtypes: float64(7), int64(3), object(6)
memory usage: 3.6+ MB

In [22]:
data.head()

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,WARD,ANC,DISTRICT,LATITUDE,LONGITUDE,OBJECTID
0,396384.27,137427.7600,24054605,2024/04/12 14:24:15+00,DAY,OTHERS,THEFT F/AUTO,1100 - 1199 BLOCK OF 18TH STREET NW,396384.270000,137427.760000,2,2C,2.0,38.904699,-77.041686,666213423
1,395709.91,137490.9400,24056000,2024/04/14 23:56:40+00,EVENING,OTHERS,THEFT/OTHER,2200 - 2299 BLOCK OF M STREET NW,395709.910000,137490.940000,2,2A,2.0,38.905265,-77.049461,666213424
2,397497.55,137053.1300,24056385,2024/04/15 17:42:57+00,DAY,OTHERS,THEFT/OTHER,1200 - 1299 BLOCK OF I STREET NW,397497.550000,137053.130000,2,2C,2.0,38.901328,-77.028849,666213769
3,400040.61,129046.4721,18060158,2024/07/30 04:00:00+00,MIDNIGHT,GUN,HOMICIDE,400 - 599 BLOCK OF CHESAPEAKE STREET SE,400040.610046,129046.472149,8,8E,7.0,38.829204,-76.999532,666236835
4,397171.11,137408.2500,24013789,2024/01/28 07:33:28+00,MIDNIGHT,OTHERS,THEFT/OTHER,1100 - 1199 BLOCK OF VERMONT AVENUE NW,397171.110000,137408.250000,2,2C,2.0,38.904526,-77.032614,666239683